// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DMEClient is the client API for DME service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DMEClient interface {
	RequestAccess(ctx context.Context, in *AccesRequest, opts ...grpc.CallOption) (*AccesRequest, error)
}

type dMEClient struct {
	cc grpc.ClientConnInterface
}

func NewDMEClient(cc grpc.ClientConnInterface) DMEClient {
	return &dMEClient{cc}
}

func (c *dMEClient) RequestAccess(ctx context.Context, in *AccesRequest, opts ...grpc.CallOption) (*AccesRequest, error) {
	out := new(AccesRequest)
	err := c.cc.Invoke(ctx, "/proto.DME/requestAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DMEServer is the server API for DME service.
// All implementations must embed UnimplementedDMEServer
// for forward compatibility
type DMEServer interface {
	RequestAccess(context.Context, *AccesRequest) (*AccesRequest, error)
	mustEmbedUnimplementedDMEServer()
}

// UnimplementedDMEServer must be embedded to have forward compatible implementations.
type UnimplementedDMEServer struct {
}

func (UnimplementedDMEServer) RequestAccess(context.Context, *AccesRequest) (*AccesRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAccess not implemented")
}
func (UnimplementedDMEServer) mustEmbedUnimplementedDMEServer() {}

// UnsafeDMEServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DMEServer will
// result in compilation errors.
type UnsafeDMEServer interface {
	mustEmbedUnimplementedDMEServer()
}

func RegisterDMEServer(s grpc.ServiceRegistrar, srv DMEServer) {
	s.RegisterService(&DME_ServiceDesc, srv)
}

func _DME_RequestAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMEServer).RequestAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DME/requestAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMEServer).RequestAccess(ctx, req.(*AccesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DME_ServiceDesc is the grpc.ServiceDesc for DME service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DME_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DME",
	HandlerType: (*DMEServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "requestAccess",
			Handler:    _DME_RequestAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/nodes.proto",
}
